FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.11.1-slim as build

WORKDIR /dapp-portal

ADD . /dapp-portal

RUN npm install && npm run generate:node:nexus

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine3.18

RUN mkdir /build

COPY --from=build /dapp-portal/dist /dist

CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
